// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	types "github.com/comptag/bobcat-lamp/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// LabResult is an autogenerated mock type for the LabResult type
type LabResult struct {
	mock.Mock
}

// IsPositive provides a mock function with given fields:
func (_m *LabResult) IsPositive() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Patient provides a mock function with given fields:
func (_m *LabResult) Patient() types.Patient {
	ret := _m.Called()

	var r0 types.Patient
	if rf, ok := ret.Get(0).(func() types.Patient); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.Patient)
	}

	return r0
}
