// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	msg "github.com/comptag/bobcat-lamp/internal/msg"
	mock "github.com/stretchr/testify/mock"

	types "github.com/comptag/bobcat-lamp/internal/types"
)

// MessageFactory is an autogenerated mock type for the MessageFactory type
type MessageFactory struct {
	mock.Mock
}

// Create provides a mock function with given fields: result
func (_m *MessageFactory) Create(result types.LabResult) msg.Message {
	ret := _m.Called(result)

	var r0 msg.Message
	if rf, ok := ret.Get(0).(func(types.LabResult) msg.Message); ok {
		r0 = rf(result)
	} else {
		r0 = ret.Get(0).(msg.Message)
	}

	return r0
}
